#!/bin/bash


getHash(){
   local U="$1"
   grep -e "^$U:" /etc/shadow|cut -d ":" -f2
}
SRC="$1"
DST="$2"
ACT="$3"


if [ "$ACT" = "check" ];then
   if [ "$(getHash "$SRC")" != "$(getHash "$DST")" ];then
     exit 1 
   else
     exit 0
   fi 
elif [ "$ACT" = "set" ];then
   echo "$DST:$(getHash "$SRC")" | chpasswd -e
   exit $?
else
   echo "$0 src-user dst-user"
fi
