colorscheme lucius

"-----MY PARAMETERS-----

set shell=/bin/bash

"Linelenght optimized for DIN A4
set textwidth=75

"Full color support in terminal
set t_Co=256

set nobackup

"Syntax-Highlighting enable
syntax enable

set number

"Set tabs depth up to 2 characters
set ts=2

"Indent when moving to the next line while writing code
"set autoindent

"Expand tabs into spaces
set expandtab

set shiftwidth=4

set cursorline

"show the matching part of the pair for [] {} and ()
set showmatch

" Highlighting search matches
set hlsearch


" enable all Python syntax highlighting features
let python_highlight_all = 1


""" VUNDLE Vim Package Manager
" no vi compat
set nocompatible

" filetype func off
filetype off

" initialize vundle
"set rtp+=~/.vim/bundle/Vundle.vim

"call vundle#begin()
"" start- all plugins below
"
"Plugin 'VundleVim/Vundle.vim'
"Plugin 'scrooloose/nerdtree.git'
"Bundle 'chase/vim-ansible-yaml'
"" stop - all plugins above
"call vundle#end()

" filetype func on
filetype plugin indent on

" NERDTree shortcut
map <C-n> :NERDTreeToggle<CR>
" Resize a wirth of NERDTre
"map <C-o> :vertical resize + 2


" More natural split opening
set splitbelow
set splitright

" Mouse Support
"set mouse=a
